# -*- coding: utf-8 -*-
"""Copy of AYLIN_ BAYAT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wp5DUduLUkhgbCCzzJVyyZEvmN5tgMJC
"""

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number: "))
num4 = int(input("Enter the fourth number: "))
num5 = int(input("Enter the fifth number: "))

total = num1 + num2 + num3 + num4 + num5

if total < 13:
    print("magmo add somma kam tar az 13 ast")
else:
    print("magmo add soma bala tar az 13 ast ")

input("baray korog enter ra bezanid.")